package com.leanix.simple.restservice.core;

import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;

@Entity
@Table(name = "todo")
@NamedQueries(
    {
        @NamedQuery(
            name = "com.leanix.simple.restservice.core.Todo.findAll",
            query = "SELECT t FROM Todo t"
        ),
        @NamedQuery(
                name = "com.leanix.simple.restservice.core.Todo.findByContent",
                query = "select t from Todo t "
                        + "where t.name like :name "
                		+ "or t.description like :name"
            )
})
public class Todo {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int id;
	
	@Column(name = "name")
	private String name;

	@Column(name = "description")
	private String description;
	
	@OneToMany(targetEntity = Task.class, mappedBy = "todo", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
	List<Task> tasks;

	public Todo() {
	}

	/**
     * A constructor to create todos. Id is not passed, cause it's auto-generated by RDBMS.
     *
     * @param name todo name
     * @param description todo description
     */
	public Todo(String name, String description) {
		this.name = name;
		this.description = description;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public List<Task> getTasks() {
		return tasks;
	}

	public void setTasks(List<Task> tasks) {
		this.tasks = tasks;
	}
}
